### ISSUE TITLE
Encountered the following error after deploying with docker

### ISSUE THREAD

**Issue by VMCoud** [iFargle/headscale-webui#104]
[2023-05-26 16:29:48 +0800] [1] [INFO] Starting gunicorn 20.1.0
[2023-05-26 16:29:48 +0800] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
[2023-05-26 16:29:48 +0800] [1] [INFO] Using worker: sync
[2023-05-26 16:29:48 +0800] [9] [INFO] Booting worker with pid: 9
[2023-05-26 16:29:49,045] INFO in server: Headscale-WebUI Version:  v0.6.2 / main
[2023-05-26 16:29:49,046] INFO in server: LOG LEVEL SET TO INFO
[2023-05-26 16:29:49,046] INFO in server: DEBUG STATE:  False
[2023-05-26 16:29:49,046] INFO in server: Loading basic auth libraries and configuring app...
[2023-05-26 16:30:06 +0800] [9] [ERROR] Error handling request /
Traceback (most recent call last):
  File "/app/.venv/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/app/.venv/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 169, in handle_request
    resp, environ = wsgi.create(req, client, addr,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/gunicorn/http/wsgi.py", line 183, in create
    path_info = path_info.split(script_name, 1)[1]
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
[2023-05-26 16:30:42 +0800] [1] [CRITICAL] WORKER TIMEOUT (pid:9)
[2023-05-26 16:30:42 +0800] [9] [INFO] Worker exiting (pid: 9)
[2023-05-26 16:30:42 +0800] [10] [INFO] Booting worker with pid: 10
[2023-05-26 16:30:42,699] INFO in server: Headscale-WebUI Version:  v0.6.2 / main
[2023-05-26 16:30:42,699] INFO in server: LOG LEVEL SET TO INFO
[2023-05-26 16:30:42,700] INFO in server: DEBUG STATE:  False
[2023-05-26 16:30:42,700] INFO in server: Loading basic auth libraries and configuring app...
[2023-05-26 16:31:13 +0800] [1] [CRITICAL] WORKER TIMEOUT (pid:10)
[2023-05-26 16:31:13 +0800] [10] [INFO] Worker exiting (pid: 10)
[2023-05-26 16:31:13 +0800] [11] [INFO] Booting worker with pid: 11
[2023-05-26 16:31:13,797] INFO in server: Headscale-WebUI Version:  v0.6.2 / main
[2023-05-26 16:31:13,797] INFO in server: LOG LEVEL SET TO INFO
[2023-05-26 16:31:13,797] INFO in server: DEBUG STATE:  False
[2023-05-26 16:31:13,797] INFO in server: Loading basic auth libraries and configuring app...
[2023-05-26 16:31:44 +0800] [1] [CRITICAL] WORKER TIMEOUT (pid:11)
[2023-05-26 16:31:44 +0800] [11] [INFO] Worker exiting (pid: 11)
[2023-05-26 16:31:44 +0800] [12] [INFO] Booting worker with pid: 12
[2023-05-26 16:31:44,894] INFO in server: Headscale-WebUI Version:  v0.6.2 / main
[2023-05-26 16:31:44,894] INFO in server: LOG LEVEL SET TO INFO
[2023-05-26 16:31:44,894] INFO in server: DEBUG STATE:  False
[2023-05-26 16:31:44,894] INFO in server: Loading basic auth libraries and configuring app...
[2023-05-26 16:32:15 +0800] [1] [CRITICAL] WORKER TIMEOUT (pid:12)
[2023-05-26 16:32:15 +0800] [12] [INFO] Worker exiting (pid: 12)
[2023-05-26 16:32:15 +0800] [13] [INFO] Booting worker with pid: 13
[2023-05-26 16:32:15,986] INFO in server: Headscale-WebUI Version:  v0.6.2 / main
[2023-05-26 16:32:15,986] INFO in server: LOG LEVEL SET TO INFO
[2023-05-26 16:32:15,986] INFO in server: DEBUG STATE:  False
[2023-05-26 16:32:15,986] INFO in server: Loading basic auth libraries and configuring app...
[2023-05-26 16:32:46 +0800] [1] [CRITICAL] WORKER TIMEOUT (pid:13)
[2023-05-26 16:32:46 +0800] [13] [INFO] Worker exiting (pid: 13)
[2023-05-26 16:32:46 +0800] [14] [INFO] Booting worker with pid: 14
[2023-05-26 16:32:47,143] INFO in server: Headscale-WebUI Version:  v0.6.2 / main
[2023-05-26 16:32:47,143] INFO in server: LOG LEVEL SET TO INFO
[2023-05-26 16:32:47,143] INFO in server: DEBUG STATE:  False
[2023-05-26 16:32:47,143] INFO in server: Loading basic auth libraries and configuring app...

**Comment by VMCoud** [comment]
root@VM-0-17-debian:/home/Admin/headscale/config# curl 127.0.0.1:5000
<html>
  <head>
    <title>Internal Server Error</title>
  </head>
  <body>
    <h1><p>Internal Server Error</p></h1>
    
  </body>
</html>

**Comment by VMCoud** [comment]
Trying to access http://127.0.0.1:5000/admin will prompt 504 no response

**Comment by VMCoud** [comment]
[2023-05-26 16:56:06 +0800] [1] [INFO] Starting gunicorn 20.1.0
[2023-05-26 16:56:06 +0800] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
[2023-05-26 16:56:06 +0800] [1] [INFO] Using worker: sync
[2023-05-26 16:56:06 +0800] [8] [INFO] Booting worker with pid: 8
[2023-05-26 16:56:07,213] INFO in server: Headscale-WebUI Version:  v0.6.2 / main
[2023-05-26 16:56:07,213] INFO in server: LOG LEVEL SET TO INFO
[2023-05-26 16:56:07,213] INFO in server: DEBUG STATE:  False
[2023-05-26 16:56:07,213] INFO in server: Loading basic auth libraries and configuring app...
[2023-05-26 16:56:50 +0800] [1] [CRITICAL] WORKER TIMEOUT (pid:8)
[2023-05-26 16:56:50 +0800] [8] [INFO] Worker exiting (pid: 8)
[2023-05-26 16:56:50 +0800] [9] [INFO] Booting worker with pid: 9
[2023-05-26 16:56:50,898] INFO in server: Headscale-WebUI Version:  v0.6.2 / main
[2023-05-26 16:56:50,898] INFO in server: LOG LEVEL SET TO INFO
[2023-05-26 16:56:50,898] INFO in server: DEBUG STATE:  False
[2023-05-26 16:56:50,898] INFO in server: Loading basic auth libraries and configuring app...
[2023-05-26 16:57:26 +0800] [1] [CRITICAL] WORKER TIMEOUT (pid:9)
[2023-05-26 16:57:26 +0800] [9] [INFO] Worker exiting (pid: 9)
[2023-05-26 16:57:26 +0800] [10] [INFO] Booting worker with pid: 10
[2023-05-26 16:57:27,044] INFO in server: Headscale-WebUI Version:  v0.6.2 / main
[2023-05-26 16:57:27,044] INFO in server: LOG LEVEL SET TO INFO
[2023-05-26 16:57:27,044] INFO in server: DEBUG STATE:  False
[2023-05-26 16:57:27,044] INFO in server: Loading basic auth libraries and configuring app...
[2023-05-26 16:57:27 +0800] [10] [ERROR] Error handling request /
Traceback (most recent call last):
  File "/app/.venv/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/app/.venv/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 169, in handle_request
    resp, environ = wsgi.create(req, client, addr,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/gunicorn/http/wsgi.py", line 183, in create
    path_info = path_info.split(script_name, 1)[1]
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
[2023-05-26 16:57:27 +0800] [10] [ERROR] Error handling request /favicon.ico
Traceback (most recent call last):
  File "/app/.venv/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/app/.venv/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 169, in handle_request
    resp, environ = wsgi.create(req, client, addr,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/gunicorn/http/wsgi.py", line 183, in create
    path_info = path_info.split(script_name, 1)[1]
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
