### ISSUE TITLE
IndexError when trying to load front page

### ISSUE THREAD

**Issue by genpfault** [iFargle/headscale-webui#105]
Getting an `IndexError` when trying to load the front page (http://localhost:5000) with today's fac78823a3:

```none
$ poetry run gunicorn -b 0.0.0.0:5000 server:app
[2023-05-30 14:43:59 -0500] [18079] [INFO] Starting gunicorn 20.1.0
[2023-05-30 14:43:59 -0500] [18079] [INFO] Listening at: http://0.0.0.0:5000 (18079)
[2023-05-30 14:43:59 -0500] [18079] [INFO] Using worker: sync
[2023-05-30 14:43:59 -0500] [18082] [INFO] Booting worker with pid: 18082
[2023-05-30 14:44:00,034] INFO in server: Headscale-WebUI Version:   /
[2023-05-30 14:44:00,034] INFO in server: LOG LEVEL SET TO DEBUG
[2023-05-30 14:44:00,035] INFO in server: DEBUG STATE:  True
[2023-05-30 14:44:00,035] INFO in server: Loading basic auth libraries and configuring app...
[2023-05-30 14:44:04 -0500] [18082] [ERROR] Error handling request /
Traceback (most recent call last):
  File "/home/genpfault/.cache/pypoetry/virtualenvs/headscale-webui-wbLfGfH0-py3.11/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/genpfault/.cache/pypoetry/virtualenvs/headscale-webui-wbLfGfH0-py3.11/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 169, in handle_request
    resp, environ = wsgi.create(req, client, addr,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/genpfault/.cache/pypoetry/virtualenvs/headscale-webui-wbLfGfH0-py3.11/lib/python3.11/site-packages/gunicorn/http/wsgi.py", line 183, in create
    path_info = path_info.split(script_name, 1)[1]
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

`.env`:

```none
TZ="UTC"
COLOR="blue-grey"
HS_SERVER=http://example.com:8080
KEY="5N1M48fU7aOWJMTCmp/1vTNp4E462c/quRvE4IcJoO8="
SCRIPT_NAME=/tmp/admin
DATA_DIRECTORY=/tmp/data
DOMAIN_NAME=http://localhost:8080
AUTH_TYPE="Basic"
LOG_LEVEL="Debug"
BASIC_AUTH_USER="admin"
BASIC_AUTH_PASS="admin"
GIT_COMMIT=""
GIT_BRANCH=""
APP_VERSION=""
BUILD_DATE=""
HS_VERSION=""
```

**Comment by iFargle** [comment]
Make sure you don't have hanging/empty machines / routes
On your headscale server, run "headscale routes list" and "headscale machines list" and delete empty items.  

Also be sure your SCRIPT_NAME is set properly -- /tmp/admin looks incorrect unless you're accessing it at http://localhost:5000/tmp/admin
