### ISSUE TITLE
ValueError: Fernet key must be 32 url-safe base64-encoded bytes.

### ISSUE THREAD

**Issue by dacrudg** [iFargle/headscale-webui#148]
When I insert the API key then click "Save" I get this in the error log (test doesn't work either):

headscalewebui     | [2024-12-11 06:17:31,798] ERROR in app: Exception on /api/save_key [POST]
headscalewebui     | Traceback (most recent call last):
headscalewebui     |   File "/app/.venv/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
headscalewebui     |     response = self.full_dispatch_request()
headscalewebui     |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
headscalewebui     |   File "/app/.venv/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
headscalewebui     |     rv = self.handle_user_exception(e)
headscalewebui     |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
headscalewebui     |   File "/app/.venv/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
headscalewebui     |     rv = self.dispatch_request()
headscalewebui     |          ^^^^^^^^^^^^^^^^^^^^^^^
headscalewebui     |   File "/app/.venv/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
headscalewebui     |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
headscalewebui     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
headscalewebui     |   File "/app/server.py", line 114, in decorated
headscalewebui     |     return view_func(*args, **kwargs)
headscalewebui     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
headscalewebui     |   File "/app/server.py", line 350, in save_key_page
headscalewebui     |     file_written  = headscale.set_api_key(api_key)
headscalewebui     |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
headscalewebui     |   File "/app/headscale.py", line 47, in set_api_key
headscalewebui     |     fernet         = Fernet(encryption_key)
headscalewebui     |     ^^^^^^^^^^^^^^^^^^^^^^
headscalewebui     |   File "/app/.venv/lib/python3.11/site-packages/cryptography/fernet.py", line 39, in __init__
headscalewebui     |     raise ValueError(
headscalewebui     | ValueError: Fernet key must be 32 url-safe base64-encoded bytes.

This is with headscale 0.23.0.

Any help would be much appreciated thank you

**Comment by pyxfluff** [comment]
Also having this issue
