### ISSUE TITLE
Is it just me or does "Overview" not working?

### ISSUE THREAD

**Issue by trading-bl** [iFargle/headscale-webui#74]

**Comment by iFargle** [comment]
Can you post your logs and your compose yaml? It's possible I'm reading the wrong file maybe.

**Comment by tobru** [comment]
I get:

```
[2023-04-05 21:54:07,292] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/app/.venv/lib/python3.11/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/server.py", line 114, in decorated
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/server.py", line 155, in overview_page
    render_page       = renderer.render_overview(),
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/renderer.py", line 219, in render_overview
    if config_yaml["derp"]["paths"]: pass
       ~~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'paths'
```

on the Overview page

**Comment by MarekPikula** [comment]
That means that in your headscale config, you have the `derp` key, but it doesn't have the `paths` key. Change it to an empty list like it's done in the example configuration (https://github.com/juanfont/headscale/blob/main/config-example.yaml#L114). The bug will be addressed in the pending refactor tracked in #73.
