### ISSUE TITLE
Docker fails to start after update to 0.7.0

### ISSUE THREAD

**Issue by dinkonin** [iFargle/headscale-webui#91]
My docker container failes to start after update with this error:
```
headscale-webui  | [2023-04-22 10:37:12 +0300] [1] [INFO] Starting gunicorn 20.1.0
headscale-webui  | [2023-04-22 10:37:12 +0300] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
headscale-webui  | [2023-04-22 10:37:12 +0300] [1] [INFO] Using worker: sync
headscale-webui  | [2023-04-22 10:37:12 +0300] [8] [INFO] Booting worker with pid: 8
headscale-webui  | Failed to find attribute 'app' in 'server'.
headscale-webui  | [2023-04-22 10:37:12 +0300] [8] [INFO] Worker exiting (pid: 8)
headscale-webui  | Job "register_scheduler.<locals>.renew_api_key (trigger: interval[1:00:00], next run at: 2023-04-22 11:37:12 EEST)" raised an exception
headscale-webui  | Traceback (most recent call last):
headscale-webui  |   File "/app/.venv/lib/python3.11/site-packages/apscheduler/executors/base.py", line 125, in run_job
headscale-webui  |     retval = job.func(*job.args, **job.kwargs)
headscale-webui  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
headscale-webui  |   File "/app/server.py", line 377, in renew_api_key
headscale-webui  |     if app.ensure_sync(headscale.renew_api_key)() is None:  # type: ignore
headscale-webui  |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
headscale-webui  |   File "/app/.venv/lib/python3.11/site-packages/asgiref/sync.py", line 213, in __call__
headscale-webui  |     loop_future = loop_executor.submit(
headscale-webui  |                   ^^^^^^^^^^^^^^^^^^^^^
headscale-webui  |   File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 169, in submit
headscale-webui  |     raise RuntimeError('cannot schedule new futures after '
headscale-webui  | RuntimeError: cannot schedule new futures after interpreter shutdown
headscale-webui  | /usr/local/lib/python3.11/traceback.py:240: RuntimeWarning: coroutine 'AsyncToSync.main_wrap' was never awaited
headscale-webui  |   tb.tb_frame.clear()
headscale-webui  | RuntimeWarning: Enable tracemalloc to get the object allocation traceback
headscale-webui  | [2023-04-22 10:37:13 +0300] [1] [INFO] Shutting down: Master
headscale-webui  | [2023-04-22 10:37:13 +0300] [1] [INFO] Reason: App failed to load.
```

Reverting to  image: ghcr.io/ifargle/headscale-webui:v0.6.1 fixes the issue.

**Comment by iFargle** [comment]
Currently working on it!  We had a major rewrite.  I should have done more testing.  I'll push to v0.7.1 when complete

**Comment by iFargle** [comment]
I've rolled back 0.7.1.  Latest is now 0.6.1 -- A fresh image will be available in about an hour.
